kamabzalov/admss-client

src/dashboard/common/form/inputs/index.tsx
src/dashboard/index.css
src/dashboard/inventory/form/purchase/consign/index.css
src/dashboard/inventory/form/purchase/consign/index.tsx
src/dashboard/inventory/form/purchase/floorplan/index.tsx

Пока общая проблема по всей форме - сохраненние currency xx.xx -> xx.00

Added form

---

src/assets/styles/global.css
src/dashboard/header/index.css
src/dashboard/header/index.tsx
src/dashboard/index.css
src/dashboard/sidebar/index.css

Изменения в сайдбаре в данный момент затрагивают только ширины (логика collapsed-expanded будет реализована в https://github.com/kamabzalov/admss-client/issues/897) для корреткного отображения остального контента на странице, после изменений в шапке. Без этих изменений весь контент просто "поехал", поэтому пришлось вносить коррективы в sidebar & dashoard main styles.

#894: Implement design updates for the header

---

src/assets/styles/global.css
src/dashboard/header/index.css
src/dashboard/header/index.tsx
src/dashboard/index.css
src/dashboard/index.tsx
src/dashboard/sidebar/index.css
src/dashboard/sidebar/index.tsx
src/store/stores/user/index.tsx

Так же в рамках задачи были изменены размеры шрифтов и иконок в соответствии с дизайном. 
Временно добавлен (пока ждем ответа дизайнера) tooltip для отображения названия пунктов меню при collapsed состоянии сайдменю. Если данные подсказки излишни - вырежу отдельным коммитом.

#897: rework sidebar design

---

.env.development
src/http/index.ts
src/http/services/auth.service.ts
src/sign/sign-in/index.tsx

Перекинул основные настройки (url/version/etc) в .env (development), а за версию приложения взял текущую версию API (Swagger).
*так же добавил обработку ошибок (и на случай отсутствия коннекта) и переписал then на async/await (как и везде, по возможности)*

#917: add app version to auth payload

---

src/dashboard/deals/form/index.tsx
src/dashboard/index.tsx
src/http/routes/ErrorBoundary.tsx
src/http/services/deals.service.ts
src/index.tsx
src/not-found/index.tsx
src/store/stores/deal/index.ts

Добавил так же общий компонент обработки ошибок, и что-бы в дальнейшем на NotFound перекидывало именно при статус коде 404.
*так же в дальнейшем хочу именновать PR таким способом, что-бы избегать путанницы с номером PR (#number)*

[task-916] Fix app crash on deal save error with proper error handling

---

src/dashboard/deals/common/index.tsx
src/dashboard/deals/form/index.tsx
src/dashboard/deals/index.css
src/store/stores/deal/index.ts

Так же изменил ширину левой части формы (выбор вкладки) и название Odometer -> Odometer Disclosure.

#914: add deal card header info

---

src/common/constants/regex.ts
src/dashboard/contacts/form/general-info/tabs/general-cobuyer/index.tsx
src/dashboard/contacts/form/general-info/tabs/general/index.tsx
src/dashboard/contacts/form/general-info/tabs/identification-cobuyer/index.tsx
src/dashboard/contacts/form/general-info/tabs/identification/index.tsx
src/dashboard/contacts/form/index.tsx

Добавил валидацию для имен так же и для Cobuyer.

#913: add name validation (only letters) / remove identification inputs disabled state

---

src/dashboard/inventory/form/index.tsx
src/dashboard/inventory/index.css

Добавил несколько значений размеров согласно дизайна, при этом для адаптивности привязал высоту блока к высоте экрана, ограничив максимальную высоту согласно значений дизайна, но при необходимости ее можно и убрать, потому что на слишком больших разрешениях контент будет занимать не всю высоту экрана.

#935: add menu scrolling

---

src/dashboard/profile/generalSettings/other/index.css
src/dashboard/profile/generalSettings/other/index.tsx

Я ограничил длинный текст согласно комментарию https://github.com/kamabzalov/admss-client/issues/918#issuecomment-2752336175, но в дизайне я не увидел тултип именно для этой вкладки.

#918: add input focus while new example create & description display limit

---

src/common/constants/regex.ts

Так же добавил поддержку дефисов (кроме пробелов), потому что у нас есть контакты, у которых есть дефис в имени/фамилии.

#913: add support for spaces and hyphens in contact name

---

src/dashboard/tasks/add-task-dialog/index.tsx

Заметил, что в полях поиска сейчас отсутствует возможность ввода пробела. Я не могу сказать баг это, или это было в требовании при разработке компонента поиска (не помню).

#942: fix data entry in search input field

---

src/dashboard/tasks/add-task-dialog/index.tsx

https://github.com/kamabzalov/admss-client/pull/952#issue-2954030871 - фикс данного комментария.

#942: allow spaces in search fields

---

src/common/models/reports/index.ts
src/dashboard/reports/common/drag-and-drop/index.tsx
src/dashboard/reports/common/panel-content/index.tsx
src/dashboard/reports/form/common/index.tsx
src/dashboard/reports/form/edit/index.tsx
src/dashboard/reports/form/index.css
src/dashboard/reports/form/index.tsx
src/http/services/reports.service.ts
src/store/stores/report/index.tsx

В рамках текущей задачи так же изменил кнопки preview / download так как они пересекаются с требованиями текущей задачи (добавление дополнительного поля для выбора коллекций).

#946: enable collection selection in report create/update form

---

src/common/models/reports/index.ts
src/dashboard/reports/common/report-parameters/index.tsx
src/dashboard/reports/form/edit/index.tsx
src/dashboard/reports/index.css
src/store/stores/report/index.tsx

Фикс некорреткной обработки при инициализации дропа (multiselect). Из-за разницы интерфейсов (itemuid, itemUID, collectionuid) ошибочно обрабатывались изначальние значения дропа.

#946: fix dropdown initial select values

---

src/common/helpers/index.ts
src/dashboard/tasks/add-task-dialog/index.css
src/dashboard/tasks/add-task-dialog/index.tsx

Так же поправил стили модального окна (без учета кнопок смены статуса) и добавил правильное чтение и запись дат (в соответствии с инструкциями бекендера)

#942: fix task date validation & added server date parser

---

src/dashboard/reports/form/edit/column-select/index.tsx
src/dashboard/reports/form/index.css

Так же добавил адаптивную ширину для колонок выбора при разных ширинах экрана, что-бы не вылезало за пределы формы.

#946: change report dataSet select template

---

src/dashboard/contacts/form/general-info/tabs/general/index.tsx
src/store/stores/contact/index.ts

https://github.com/kamabzalov/admss-client/issues/913#issuecomment-2776395888 - пофикшено. Проблема была в однаковом именовании переменной "contact" - эта переменная была как локально, так и с таким же именем приходила с сервера, что и вызывало сбой в заполнении пустых полей.
---
_p.s. так же изменил по аналогии с coBuyer вызов функции с множественных на вызов единожды с передачей массива аргументов._

#913: Optimize handleFileChange in ContactsGeneralInfo and fix empty fields issue

---

src/dashboard/contacts/form/general-info/tabs/address/index.tsx
src/dashboard/inventory/form/export-web/price/index.tsx
src/dashboard/inventory/form/purchase/consign/index.tsx

Я так понимаю задача старая? Потому что дизайн уже давно не такой, как на скриншоте, и для даты есть лейбл. Прошелся по всем формам, и добавил там где не было.

#974: add float labels

---

src/dashboard/inventory/form/index.tsx
src/dashboard/inventory/form/media-data/audio/index.tsx
src/dashboard/inventory/form/media-data/documents/index.tsx
src/dashboard/inventory/form/media-data/images/index.tsx
src/dashboard/inventory/form/media-data/links/index.css
src/dashboard/inventory/form/media-data/links/index.tsx
src/dashboard/inventory/form/media-data/video/index.tsx
src/http/services/media.service.ts
src/store/stores/inventory/index.ts

Пришлось изменять логику запроса media в целом, из-за дублей запросов и перерисовки из-за этого.

#975: refactor inventory media components to streamline data fetching & fix link item styles

---

src/index.tsx
src/sign/sign-in/index.tsx

Просьба не мерджить до возобновления работы сервера (авторизации). Ревью запрошено для проверки текущего состояния и внесения корректировок при необходимости :)

REF: change SignIn component to improve error handling & prevent navigate to dashboard without token

---

src/dashboard/index.css
src/dashboard/reports/form/index.css
src/dashboard/reports/form/index.tsx

Возможно перед мерджем стоить схлопнуть с помощью rebase историю коммитов?

#945: change drag&drop drop-point style

---

src/common/models/inventory/index.ts
src/dashboard/contacts/form/contact-info/prospecting/index.tsx
src/http/services/inventory-service.ts

Что делать с предыдущим (listprospect) ендпоинтом? Он пока в проекте, но если он не будет использоваться - вырежу следующим коммитом.

#973: add InventoryShortList API for prospecting

---

src/dashboard/deals/index.tsx

Так же исправлено дубль запроса deals при рендере таблицы.

#995: update Sale Date field to use dateeffective

---

src/dashboard/reports/common/access-dialog/index.css
src/dashboard/reports/common/access-dialog/index.tsx
src/dashboard/reports/index.css
src/dashboard/reports/index.tsx

Так же изменено диалоговое окно в соответствии с дизайном

#1028: update access dialog styles and improve click handling in reports list

---

src/dashboard/contacts/form/media-data/documents/index.tsx
src/store/stores/contact/index.ts

Так как в дизайне нет отрисовки состояний при загрузке или удаления документов, то как и было сказано - удалил полноэкранный лоадинг, заменив его на лькальный (т.е. лоадер отрабатывает теперь только в списке картинок)

#1068: improved file upload processing and moved loading state locally

---

src/dashboard/common/overlay-panel/index.css
src/dashboard/common/overlay-panel/index.tsx
src/dashboard/reports/form/edit/column-select/index.css
src/dashboard/reports/form/edit/column-select/index.tsx
src/dashboard/reports/form/edit/column-select/info-panel/index.css
src/dashboard/reports/form/edit/column-select/info-panel/index.tsx
src/dashboard/reports/form/index.css
src/dashboard/reports/form/index.tsx
src/dashboard/sidebar/index.css
src/store/stores/user/index.tsx

Добавлена анимация пульсации исходя из статичных стилей. При дальнейшем уточнении информации - внесу изменения в анимацию отдельным коммитом.

#1139: update report form to include data set info panel & button animation

---

src/assets/styles/components/datatable.css
src/assets/styles/global.css
src/dashboard/accounts/index.css
src/dashboard/accounts/index.tsx
src/dashboard/common/form/inputs/index.css
src/dashboard/common/form/inputs/index.tsx
src/dashboard/contacts/index.css
src/dashboard/contacts/index.tsx
src/dashboard/deals/index.tsx
src/dashboard/export-web/history/index.tsx
src/dashboard/export-web/index.css
src/dashboard/reports/common/report-buttons/index.tsx

Реализовано только перемещение и правка размеров текущих компонентов, согласно описания задачи. Новые элементы (выбор колонок, типов) в данном PR не сделаны. Если будет реализация в этой же ветке - допишу отдельными коммитами.

#1178: implement GlobalSearchInput component and update datatable controls
